version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: ${POSTGRES_USERNAME}
            password: ${POSTGRES_PASSWORD}
  postgres-db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
